spring:
  datasource:
    url: jdbc:mysql://localhost:3306/products_db
    username: dev
    password: dev

  app:
    cors:
      allowedOriginPatterns:
        - http://localhost:5173
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true